using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using PolicySharp.Analyzers;
using Xunit;

namespace PolicySharp.Tests;

public sealed class GeneratedCodePolicyTests
{
    [Fact]
    public async Task NamespacePolicy_IsEnforcedInGeneratedFile()
    {
        const string source = """
        // <auto-generated/>
        namespace Sample.Domain;

        public sealed class GeneratedWorker
        {
            public void Run()
            {
                System.Diagnostics.Debug.WriteLine("generated");
            }
        }
        """;

        var diagnostics = await AnalyzeAsync(
            new DiagnosticAnalyzer[] { new PolicySharpAnalyzer() },
            source,
            Policy(
                allowNamespaces: new[] { "Sample.Domain.**" }),
            "GeneratedWorker.g.cs");

        Assert.Contains(
            diagnostics,
            diagnostic => diagnostic.Id == PolicySharpAnalyzer.NotAllowedDiagnosticId);
    }

    [Fact]
    public async Task CapabilityPolicy_IsEnforcedInGeneratedFile()
    {
        const string source = """
        // <auto-generated/>
        namespace Sample.Domain;

        public sealed class GeneratedWorker
        {
            public void Run(System.Net.Http.HttpClient client)
            {
                _ = client.GetAsync("https://example.test");
            }
        }
        """;

        var diagnostics = await AnalyzeAsync(
            new DiagnosticAnalyzer[] { new CapabilityAllowlistAnalyzer() },
            source,
            Policy(
                allowNamespaces: new[] { "Sample.Domain.**", "System.Net.Http" }),
            "GeneratedWorker.g.cs");

        Assert.Contains(
            diagnostics,
            diagnostic => diagnostic.Id == CapabilityAllowlistAnalyzer.CapabilityNotAllowedDiagnosticId);
    }

    [Fact]
    public async Task SymbolPolicy_IsEnforcedInGeneratedFile()
    {
        const string source = """
        // <auto-generated/>
        namespace Sample.Domain;

        public sealed class GeneratedWorker
        {
            public void Run()
            {
                System.Console.WriteLine("generated");
            }
        }
        """;

        var diagnostics = await AnalyzeAsync(
            new DiagnosticAnalyzer[] { new SymbolAllowlistAnalyzer() },
            source,
            Policy(
                allowNamespaces: new[] { "Sample.Domain.**", "System" },
                allowSymbols: new[] { "System.Console.ReadLine()" }),
            "GeneratedWorker.g.cs");

        Assert.Contains(
            diagnostics,
            diagnostic => diagnostic.Id == SymbolAllowlistAnalyzer.SymbolNotAllowedDiagnosticId);
    }

    private static async Task<ImmutableArray<Diagnostic>> AnalyzeAsync(
        IEnumerable<DiagnosticAnalyzer> analyzers,
        string source,
        string policy,
        string path)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(source, path: path);
        var compilation = CSharpCompilation.Create(
            "PolicySharp.GeneratedCodeTests",
            new[] { syntaxTree },
            GetPlatformReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var analyzerOptions = new AnalyzerOptions(
            ImmutableArray.Create<AdditionalText>(
                new InMemoryAdditionalText("policysharp.json", policy)));

        return await compilation
            .WithAnalyzers(analyzers.ToImmutableArray(), analyzerOptions)
            .GetAnalyzerDiagnosticsAsync();
    }

    private static IEnumerable<MetadataReference> GetPlatformReferences()
    {
        var trustedPlatformAssemblies =
            (string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")
            ?? throw new InvalidOperationException("TRUSTED_PLATFORM_ASSEMBLIES is unavailable.");

        return trustedPlatformAssemblies
            .Split(Path.PathSeparator)
            .Where(path => path.EndsWith(".dll", StringComparison.OrdinalIgnoreCase))
            .Select(path => MetadataReference.CreateFromFile(path));
    }

    private static string Policy(
        string[] allowNamespaces,
        string[]? allowSymbols = null)
    {
        var namespaces = string.Join(
            ", ",
            allowNamespaces.Select(value => $"\"{value}\""));
        var symbols = string.Join(
            ", ",
            (allowSymbols ?? Array.Empty<string>())
                .Select(value => $"\"{value}\""));

        return $$"""
        {
          "version": 1,
          "mode": "default-deny",
          "scopes": [
            {
              "id": "domain",
              "match": { "namespace": "Sample.Domain.**" },
              "allow": {
                "namespaces": [ {{namespaces}} ],
                "symbols": [ {{symbols}} ]
              }
            }
          ]
        }
        """;
    }

    private sealed class InMemoryAdditionalText : AdditionalText
    {
        private readonly SourceText _text;

        public InMemoryAdditionalText(string path, string text)
        {
            Path = path;
            _text = SourceText.From(text);
        }

        public override string Path { get; }

        public override SourceText GetText(CancellationToken cancellationToken = default) => _text;
    }
}
